server {
	listen 443 ssl;
	listen [::]:443;

	server_name ybounite.42.fr;

	# SSL settings
	ssl_protocols TLSv1.3;
	ssl_certificate /etc/nginx/ssl/server.crt;
	ssl_certificate_key /etc/nginx/ssl/server.key;

	location / {
		root /var/www/html;
		index index.php index.html;
	}

	# Handle PHP requests (adjust if using WordPress container)
	location ~ \.php$ {
		fastcgi_pass wordpress:9000;  # Proxy to WordPress (PHP-FPM)
		fastcgi_index index.php;
		fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
		include fastcgi_params;
	}
}