services:
  nginx:
    build: ./requirements/nginx/.
    container_name: nginx
    image: nginx
    depends_on:
      - wordpress
    volumes:
      - "wordpress:/var/www/html"
    ports:
      - "443:443"
    networks:
      - net-incption
    restart:  unless-stopped

  mariadb:
    build: ./requirements/mariadb/.
    container_name: mariadb
    image: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - net-incption
    restart:  unless-stopped

  wordpress:
    build: ./requirements/wordpress/.
    container_name: wordpress
    image: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - net-incption
    restart:  unless-stopped
  
  redis:
    build: ./requirements/bonus/redis/.
    container_name: redis
    image: redis
    networks:
      - net-incption
    # volumes
    restart: unless-stopped
  ftp:
    build: ./requirements/bonus/ftp/.
    container_name: ftp
    image: ftp
    ports:
      - "21:21"
      - "10000-10100:10000-10100"
    env_file:
      - .env
    networks:
      - net-incption
    volumes:
      - wordpress:/var/www/html
    restart: unless-stopped
  portfelio:
    build: ./requirements/bonus/portfelio/.
    container_name: portfelio
    image: portfelio:0.1
    ports:
      - "8081:8081"
    networks:
      - net-incption
    restart: unless-stopped
  adminer:
    build: ./requirements/bonus/adminer/.
    container_name: adminer
    image: adminer:0.1
    depends_on:
      - mariadb
    ports:
      - "600:80"
    networks:
      - net-incption
    restart: unless-stopped

networks:
  net-incption:
    driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: '/home/ybounite/data/wp'
      o: 'bind'

  mariadb:
    driver: local
    driver_opts:
      type: none
      device: '/home/ybounite/data/db'
      o: 'bind'
